# setup.ps1  --  First-time setup wizard for a new user / new machine
#
# Guides a new colleague (or a fresh install) through configuring the
# AI research infrastructure from scratch.
#
# Prerequisites (install manually before running):
#   - Claude Code CLI  https://claude.ai/download  then: claude login
#   - Git              https://git-scm.com/download/win
#   - MiKTeX           https://miktex.org/download
#   - VS Code          https://code.visualstudio.com/
#   - Strawberry Perl  https://strawberryperl.com/  (for latexdiff in submit.ps1)
#
# Usage:
#   helpi 21
#   .\setup.ps1
#

$sep    = "  " + ("-" * 65)
$aiRoot = Split-Path $PSScriptRoot -Parent   # AI_auto/ (parent of scripts/)

Write-Host ""
Write-Host "  AI Research Infrastructure -- First-time Setup" -ForegroundColor Cyan
Write-Host "  This wizard writes config.local.ps1 and wires up your shell profile." -ForegroundColor DarkGray
Write-Host $sep -ForegroundColor DarkGray

# ── Step 1: Publications root ─────────────────────────────────────
Write-Host ""
Write-Host "  [1/7] Publications root folder" -ForegroundColor DarkYellow
Write-Host "  This is the folder that contains all your Pub_* / Pro_* / PhD_* project folders." -ForegroundColor DarkGray
Write-Host "  Example: C:\Users\YourName\OneDrive\Research\Publikationer" -ForegroundColor DarkGray
Write-Host ""
$pubRoot = (Read-Host "  Path to publications root").Trim().Trim('"')
if (!(Test-Path $pubRoot)) {
    Write-Host "  Path does not exist. Creating it..." -ForegroundColor Yellow
    New-Item -ItemType Directory -Path $pubRoot -Force | Out-Null
}
Write-Host "  OK: $pubRoot" -ForegroundColor Green

# ── Step 2: Git identity ──────────────────────────────────────────
Write-Host ""
Write-Host "  [2/7] Git identity" -ForegroundColor DarkYellow
$defaultUser  = git config --global user.name  2>$null
$defaultEmail = git config --global user.email 2>$null
$gitUser  = (Read-Host "  Your name  (default: $defaultUser)").Trim()
$gitEmail = (Read-Host "  Your email (default: $defaultEmail)").Trim()
if (!$gitUser)  { $gitUser  = $defaultUser  }
if (!$gitEmail) { $gitEmail = $defaultEmail }
if ($gitUser)  { git config --global user.name  $gitUser  }
if ($gitEmail) { git config --global user.email $gitEmail }
Write-Host "  OK: $gitUser <$gitEmail>" -ForegroundColor Green

# ── Step 3: Tool paths (detect or prompt) ────────────────────────
Write-Host ""
Write-Host "  [3/7] Tool paths" -ForegroundColor DarkYellow

$vscode = "$env:LOCALAPPDATA\Programs\Microsoft VS Code\bin\code.cmd"
if (!(Test-Path $vscode)) {
    Write-Host "  VS Code not found at default location." -ForegroundColor Yellow
    $vscode = (Read-Host "  Path to code.cmd (or leave blank to skip)").Trim().Trim('"')
}
Write-Host "  VS Code: $(if (Test-Path $vscode) { 'found' } else { 'not found -- update config.ps1 later' })" -ForegroundColor DarkGray

$miktexBin = "$env:LOCALAPPDATA\Programs\MiKTeX\miktex\bin\x64"
if (!(Test-Path "$miktexBin\latexmk.exe")) {
    Write-Host "  MiKTeX not found at default location." -ForegroundColor Yellow
    $miktexBin = (Read-Host "  Path to MiKTeX bin folder (or leave blank to skip)").Trim().Trim('"')
}
Write-Host "  MiKTeX: $(if (Test-Path "$miktexBin\latexmk.exe") { 'found' } else { 'not found -- update config.ps1 later' })" -ForegroundColor DarkGray

$latexdiffScript = "$env:LOCALAPPDATA\Programs\MiKTeX\scripts\latexdiff\latexdiff"
$strawberryPerl  = "C:\Strawberry\perl\bin\perl.exe"

# ── Step 4: Write config.local.ps1 ───────────────────────────────
Write-Host ""
Write-Host "  [4/7] Writing config.local.ps1..." -ForegroundColor DarkYellow
Write-Host "  (This file is gitignored -- it will never conflict on git pull.)" -ForegroundColor DarkGray

$localConfigPath = Join-Path $aiRoot "scripts\config.local.ps1"

$configContent = @"
# config.local.ps1  --  Machine-specific configuration for this install
# Generated by setup.ps1 on $(Get-Date -Format 'yyyy-MM-dd').
# This file is gitignored. Do not commit it.

`$pubRoot  = "$pubRoot"
`$gitUser  = "$gitUser"
`$gitEmail = "$gitEmail"
"@

[System.IO.File]::WriteAllText($localConfigPath, $configContent, [System.Text.Encoding]::UTF8)
Write-Host "  OK: config.local.ps1 written." -ForegroundColor Green

# ── Step 5: PowerShell profile (helpi) ───────────────────────────
Write-Host ""
Write-Host "  [5/7] PowerShell profile (helpi function)" -ForegroundColor DarkYellow
$profilePath = $PROFILE.CurrentUserAllHosts
$helpiLine   = "function helpi { & `"$aiRoot\scripts\helpi.ps1`" @args }"
$profileExists = Test-Path $profilePath
$profileContent = if ($profileExists) { Get-Content $profilePath -Raw -ErrorAction SilentlyContinue } else { "" }

if ($profileContent -match 'helpi') {
    Write-Host "  OK: helpi already in profile (skipped)." -ForegroundColor Green
} else {
    if (!$profileExists) { New-Item -ItemType File -Path $profilePath -Force | Out-Null }
    Add-Content $profilePath "`n# AI research infrastructure`n$helpiLine"
    Write-Host "  OK: helpi added to $profilePath" -ForegroundColor Green
    Write-Host "      Restart your terminal or run: . `$PROFILE" -ForegroundColor DarkGray
}

# ── Step 6: Scheduled task (auto-sync) ───────────────────────────
Write-Host ""
Write-Host "  [6/7] Scheduled task (auto-sync every 4h)" -ForegroundColor DarkYellow
$task = Get-ScheduledTask -TaskName "AI_AutoSync" -ErrorAction SilentlyContinue
if ($task) {
    Write-Host "  OK: Task already exists (skipped)." -ForegroundColor Green
} else {
    try {
        $action   = New-ScheduledTaskAction -Execute "powershell.exe" `
                      -Argument "-NoProfile -WindowStyle Hidden -File `"$aiRoot\scripts\sync_all.ps1`""
        $trigger  = New-ScheduledTaskTrigger -RepetitionInterval (New-TimeSpan -Hours 4) -Once `
                      -At (Get-Date).Date
        $settings = New-ScheduledTaskSettingsSet -ExecutionTimeLimit (New-TimeSpan -Minutes 10) `
                      -StartWhenAvailable
        Register-ScheduledTask -TaskName "AI_AutoSync" -Action $action -Trigger $trigger `
          -Settings $settings -RunLevel Highest -Force | Out-Null
        Write-Host "  OK: Scheduled task 'AI_AutoSync' registered." -ForegroundColor Green
    } catch {
        Write-Host "  WARN: Could not register task (may need admin). Run as Administrator if needed." -ForegroundColor Yellow
    }
}

# ── Step 7: Overleaf bulk-import ─────────────────────────────────
Write-Host ""
Write-Host "  [7/7] Overleaf project import" -ForegroundColor DarkYellow
Write-Host "  This fetches all your Overleaf projects in one go and registers them automatically." -ForegroundColor DarkGray
Write-Host "  You will need your overleaf_session2 cookie:" -ForegroundColor DarkGray
Write-Host "    Log into overleaf.com -> F12 -> Application -> Cookies -> copy overleaf_session2" -ForegroundColor DarkGray
Write-Host ""
$runImport = (Read-Host "  Run Overleaf bulk-import now? [Y/n]").Trim().ToLower()
if ($runImport -eq "" -or $runImport -eq "y") {
    Write-Host ""
    & "$PSScriptRoot\fetch_overleaf_projects.ps1"
    Write-Host ""
    Write-Host "  Review the table above. If all matches look correct, run:" -ForegroundColor DarkGray
    Write-Host "    .\link_projects.ps1" -ForegroundColor White
    Write-Host "  to clone and register everything. Or re-run later: helpi 22" -ForegroundColor DarkGray
} else {
    Write-Host "  Skipped. Run later:" -ForegroundColor DarkGray
    Write-Host "    .\fetch_overleaf_projects.ps1   # fetch + match" -ForegroundColor White
    Write-Host "    .\link_projects.ps1              # clone + register" -ForegroundColor White
}

# ── Summary ───────────────────────────────────────────────────────
Write-Host ""
Write-Host $sep -ForegroundColor DarkGray
Write-Host "  Setup complete." -ForegroundColor Cyan
Write-Host ""
Write-Host "  Next steps:" -ForegroundColor White
Write-Host "  1. Install Claude Code, Git, MiKTeX, VS Code if not done (see prerequisites above)." -ForegroundColor DarkGray
Write-Host "  2. Run: claude login" -ForegroundColor DarkGray
Write-Host "  3. Copy ~/.claude/CLAUDE.md and ~/.claude/commands/ from the shared repo or a colleague." -ForegroundColor DarkGray
Write-Host "  4. Restart your terminal, then run: helpi" -ForegroundColor DarkGray
Write-Host "  5. If you skipped Overleaf import: fetch_overleaf_projects.ps1, then link_projects.ps1" -ForegroundColor DarkGray
Write-Host ""
Write-Host "  GitHub repo (for reference / updates): https://github.com/jepperich69/ai-infrastructure" -ForegroundColor DarkGray
Write-Host ""
